"""Regenerate a profile's pinned table layouts.

    python -m simoscal.tune.profiles pin <profile> <xdf> <bin>

Prints the ``table_layouts=`` block to paste into that profile's module. Run it
only against the definition file the map was authored against and a bin you
trust — the pin is a record that a human checked those two files once, and a pin
regenerated from whatever is at hand records nothing.

Why a command rather than an import-time computation: see
:func:`~simoscal.tune.profile.pin_layouts`.
"""

from __future__ import annotations

import sys
from pathlib import Path

from ...calfile import CalFile, structure_of
from ..profile import pin_layouts, replace
from . import PROFILES


def _pin(profile_name: str, xdf: str, binary: str) -> int:
    try:
        profile = PROFILES[profile_name]
    except KeyError:
        print(
            f"no profile {profile_name!r}; known: {', '.join(sorted(PROFILES))}",
            file=sys.stderr,
        )
        return 2

    cal = CalFile.open(
        xdf, binary,
        structure=structure_of(Path(binary)),
        base_offset=profile.xdf_base_offset,
        float_bug_symbols=profile.float_bug_symbols,
    )
    # Pin against the map as authored, not as already pinned: re-running with the
    # old pins in force would fail resolution on exactly the tables whose layout
    # changed, which is the case this command exists to re-record.
    digests = pin_layouts(replace(profile, table_layouts={}), cal)

    width = max(len(n) for n in digests) + 2
    print(f"#: Layout pins for {Path(xdf).name}, generated by")
    print("#: ``python -m simoscal.tune.profiles pin "
          f"{profile_name} {xdf} {binary}``.")
    print("_TABLE_LAYOUTS = {")
    for name, digest in digests.items():
        print(f'    {(chr(34) + name + chr(34) + ":"):<{width + 1}} "{digest}",')
    print("}")
    return 0


def main(argv: list[str]) -> int:
    if len(argv) != 4 or argv[0] != "pin":
        print(__doc__.strip().splitlines()[2].strip(), file=sys.stderr)
        return 2
    return _pin(argv[1], argv[2], argv[3])


if __name__ == "__main__":  # pragma: no cover - entry point
    raise SystemExit(main(sys.argv[1:]))
